function c = new_trial_cfg(p, patient_id, session_nr)
% NEW_TRIAL_CFG  Template of one trial cfg with every field in a fixed order:
% ids, stimulus, trial type and response options, timing, daq train, and the
% run-time results (empty_trial_results). All plan builders start from it,
% so every trial struct of every task has the same fields.
c = struct( ...
    'task_type', p.task_type, 'task_name', p.task_name, ...
    'patient_id', patient_id, 'session_nr', session_nr, ...
    'trial_id', NaN, 'block_id', NaN, 'rep_id', NaN, ...       % trial_id: position in the session
    'is_minimum', false, 'is_practice', false, ...             % is_minimum: within the first n_images*min_reps
    'stim_idx', NaN, 'image_file', '', 'filename', '', ...
    'axis_id', NaN, 'axis_name', '', 'spose_dim', NaN, ...       % axis_id/concept_id: indices in the set (daq)
    'concept_id', NaN, 'concept_name', '', 'things_id', NaN, ...  % spose_dim / things_id: original ids
    'inst_id', NaN, 'alpha', NaN, 'level_id', NaN, ...
    'trial_type', NaN, 'trial_type_name', '', ...              % TaskCodes.TRIAL_TYPES
    'option_axis_ids', zeros(1, p.n_options), 'option_names', {repmat({''}, 1, p.n_options)}, ...
    'option_labels', {repmat({''}, 1, p.n_options)}, 'target_pos', 0, ...  % 0 = no target shown
    'jitter_time', NaN, ...
    'daq_trial_values', []);                                   % TaskCodes.TRAIN_TRIAL values
r = empty_trial_results();
fn = fieldnames(r);
for k = 1:numel(fn), c.(fn{k}) = r.(fn{k}); end
end
